#!/bin/sh
# Generated by packmule -- offline pypi installer
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"

# Install every wheel/sdist in this directory from the bundled requirements.txt,
# without contacting any index.
pip install --no-index --find-links="$DIR" -r "$DIR/requirements.txt"
