#!/bin/sh
# Generated by packmule -- offline npm installer
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"

# Install each bundled tarball. npm resolves the bundled deps from disk.
for f in "$DIR"/*.tgz; do
  npm install "$f"
done
