#!/bin/sh
# Generated by packmule -- offline rpm installer
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"

#__PACKMULE_VERIFY__

[ "${PACKMULE_SKIP_VERIFY:-0}" = "1" ] || packmule_verify "$DIR" || exit 1

# packmule verifies each .rpm against the checksum published in the
# repository's signed-by-convention repodata, and the check above confirms the
# files survived the trip intact.  Neither is a substitute for the package
# signature itself: leave dnf's gpgcheck alone so rpm validates the vendor key
# as it normally would.  If the target does not have that key imported, import
# it (rpm --import) rather than reaching for --nogpgcheck.
if command -v dnf >/dev/null 2>&1; then
  dnf install -y --disablerepo='*' "$DIR"/*.rpm
else
  rpm -Uvh "$DIR"/*.rpm
fi
