/*
 * rpm_repo.c — indexed access to a decompressed primary.xml.
 * See rpm_repo.h for why the document is indexed rather than rescanned.
 *
 * The XML is handled by targeted string scanning rather than a full parser.
 * repodata is machine-generated by createrepo_c with a fixed, predictable
 * shape, and taking on libxml2/expat for it would be a heavy dependency for
 * a tool whose whole point is being easy to deploy somewhere isolated.
 */

#include "rpm_repo.h"
#include "registry_internal.h"
#include "utils.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── Small XML helpers ───────────────────────────────────────────────────── */

static const char *bounded(const char *hay, const char *end, const char *needle)
{
    const char *p = strstr(hay, needle);
    return (p && p < end) ? p : NULL;
}

/*
 * attr_slice — locate attribute `name` in the tag fragment [tag, limit) and
 * return a slice of its value.  Returns 0 when the attribute is absent.
 */
static int attr_slice(const char *tag, const char *limit, const char *name,
                      const char **out, size_t *out_len)
{
    char pat[64];
    int  n = snprintf(pat, sizeof(pat), "%s=", name);
    if (n < 0 || (size_t)n >= sizeof(pat))
        return 0;

    for (const char *p = tag; (p = bounded(p, limit, pat)) != NULL; p += 1) {
        /* Must be a whole attribute name: preceded by whitespace. */
        if (p > tag && p[-1] != ' ' && p[-1] != '\t' &&
            p[-1] != '\n' && p[-1] != '\r')
            continue;
        const char *v = p + strlen(pat);
        if (*v != '"' && *v != '\'')
            continue;
        char        q   = *v++;
        const char *end = memchr(v, q, (size_t)(limit - v));
        if (!end)
            return 0;
        *out     = v;
        *out_len = (size_t)(end - v);
        return 1;
    }
    return 0;
}

static char *attr_dup(const char *tag, const char *limit, const char *name)
{
    const char *v;
    size_t      n;
    if (!attr_slice(tag, limit, name, &v, &n))
        return NULL;
    return pm_strndup(v, n);
}

/* elem_slice — text content of <name>…</name> within [start, end). */
static int elem_slice(const char *start, const char *end, const char *name,
                      const char **out, size_t *out_len)
{
    char open[64], close[64];
    snprintf(open,  sizeof(open),  "<%s>",  name);
    snprintf(close, sizeof(close), "</%s>", name);

    const char *o = bounded(start, end, open);
    if (!o)
        return 0;
    o += strlen(open);
    const char *c = bounded(o, end, close);
    if (!c)
        return 0;
    *out     = o;
    *out_len = (size_t)(c - o);
    return 1;
}

/* ── Hash index ──────────────────────────────────────────────────────────── */

typedef struct CapNode {
    const char     *name;
    size_t          name_len;
    size_t         *blocks;
    size_t          n_blocks;
    size_t          cap_blocks;
    struct CapNode *next;
} CapNode;

struct RpmRepo {
    const char *xml;

    RpmBlock *blocks;
    size_t    n_blocks;
    size_t    cap_blocks;

    CapNode **provides;      /* capability name → blocks */
    CapNode **names;         /* <name> → blocks */
    size_t    nbuckets;
};

static size_t hash_slice(const char *s, size_t n, size_t nbuckets)
{
    /* FNV-1a */
    size_t h = 1469598103934665603ULL;
    for (size_t i = 0; i < n; i++) {
        h ^= (unsigned char)s[i];
        h *= 1099511628211ULL;
    }
    return h & (nbuckets - 1);
}

static void table_insert(CapNode **table, size_t nbuckets, const char *name,
                         size_t name_len, size_t block)
{
    size_t   b = hash_slice(name, name_len, nbuckets);
    CapNode *n = table[b];
    for (; n; n = n->next)
        if (n->name_len == name_len && memcmp(n->name, name, name_len) == 0)
            break;

    if (!n) {
        n = pm_calloc(1, sizeof(*n));
        n->name       = name;
        n->name_len   = name_len;
        n->cap_blocks = 4;
        n->blocks     = pm_malloc(n->cap_blocks * sizeof(size_t));
        n->next       = table[b];
        table[b]      = n;
    }

    /* The same package can list a capability more than once. */
    if (n->n_blocks > 0 && n->blocks[n->n_blocks - 1] == block)
        return;

    if (n->n_blocks == n->cap_blocks) {
        n->cap_blocks *= 2;
        n->blocks = pm_realloc(n->blocks, n->cap_blocks * sizeof(size_t));
    }
    n->blocks[n->n_blocks++] = block;
}

static int table_lookup(CapNode **table, size_t nbuckets, const char *name,
                        size_t *out, int max)
{
    size_t len = strlen(name);
    for (CapNode *n = table[hash_slice(name, len, nbuckets)]; n; n = n->next) {
        if (n->name_len != len || memcmp(n->name, name, len) != 0)
            continue;
        int k = 0;
        for (size_t i = 0; i < n->n_blocks && k < max; i++)
            out[k++] = n->blocks[i];
        return k;
    }
    return 0;
}

static void table_free(CapNode **table, size_t nbuckets)
{
    if (!table)
        return;
    for (size_t b = 0; b < nbuckets; b++) {
        CapNode *n = table[b];
        while (n) {
            CapNode *next = n->next;
            pm_free(n->blocks);
            pm_free(n);
            n = next;
        }
    }
    pm_free(table);
}

/* ── Index construction ──────────────────────────────────────────────────── */

/*
 * index_provides — hash every capability the block at `idx` provides.
 *
 * Both <rpm:provides> entries and the <file> elements are indexed: RPM
 * dependencies routinely name a path ("/usr/bin/sh", "/usr/sbin/useradd")
 * rather than a package, and a resolver that only knew about named
 * capabilities would report those as unsatisfiable.
 */
static void index_provides(RpmRepo *repo, size_t idx)
{
    const RpmBlock *b = &repo->blocks[idx];

    const char *prov = bounded(b->start, b->end, "<rpm:provides>");
    if (prov) {
        const char *pend = bounded(prov, b->end, "</rpm:provides>");
        if (!pend)
            pend = b->end;
        for (const char *e = prov;
             (e = bounded(e, pend, "<rpm:entry ")) != NULL; e += 11) {
            const char *tag_end = memchr(e, '>', (size_t)(pend - e));
            if (!tag_end)
                break;
            const char *nm;
            size_t      nlen;
            if (attr_slice(e, tag_end, "name", &nm, &nlen) && nlen > 0)
                table_insert(repo->provides, repo->nbuckets, nm, nlen, idx);
        }
    }

    for (const char *f = b->start;
         (f = bounded(f, b->end, "<file")) != NULL; ) {
        const char *tag_end = memchr(f, '>', (size_t)(b->end - f));
        if (!tag_end)
            break;
        const char *close = bounded(tag_end, b->end, "</file>");
        if (!close) {
            f = tag_end + 1;
            continue;
        }
        const char *val  = tag_end + 1;
        size_t      vlen = (size_t)(close - val);
        if (vlen > 0)
            table_insert(repo->provides, repo->nbuckets, val, vlen, idx);
        f = close + 7;
    }
}

RpmRepo *rpm_repo_index(const char *primary_xml)
{
    if (!primary_xml)
        return NULL;

    RpmRepo *repo = pm_calloc(1, sizeof(*repo));
    repo->xml = primary_xml;

    /* Locate every <package> block first, so the bucket count can be sized
     * from the real package count rather than guessed. */
    repo->cap_blocks = 1024;
    repo->blocks     = pm_malloc(repo->cap_blocks * sizeof(RpmBlock));

    for (const char *p = strstr(primary_xml, "<package ");
         p != NULL;
         p = strstr(p, "<package ")) {
        const char *end = strstr(p, "</package>");
        if (!end)
            break;
        if (repo->n_blocks == repo->cap_blocks) {
            repo->cap_blocks *= 2;
            repo->blocks = pm_realloc(repo->blocks,
                                      repo->cap_blocks * sizeof(RpmBlock));
        }
        repo->blocks[repo->n_blocks].start = p;
        repo->blocks[repo->n_blocks].end   = end;
        repo->n_blocks++;
        p = end + 10;
    }

    /* Power-of-two buckets, roughly 8 capabilities per package. */
    size_t want = repo->n_blocks * 8 + 16;
    repo->nbuckets = 1024;
    while (repo->nbuckets < want && repo->nbuckets < (1u << 22))
        repo->nbuckets <<= 1;

    repo->provides = pm_calloc(repo->nbuckets, sizeof(CapNode *));
    repo->names    = pm_calloc(repo->nbuckets, sizeof(CapNode *));

    for (size_t i = 0; i < repo->n_blocks; i++) {
        const char *nm;
        size_t      nlen;
        if (elem_slice(repo->blocks[i].start, repo->blocks[i].end,
                       "name", &nm, &nlen) && nlen > 0)
            table_insert(repo->names, repo->nbuckets, nm, nlen, i);
        index_provides(repo, i);
    }

    return repo;
}

void rpm_repo_free(RpmRepo *repo)
{
    if (!repo)
        return;
    table_free(repo->provides, repo->nbuckets);
    table_free(repo->names,    repo->nbuckets);
    pm_free(repo->blocks);
    pm_free(repo);
}

size_t rpm_repo_count(const RpmRepo *repo)
{
    return repo ? repo->n_blocks : 0;
}

const RpmBlock *rpm_repo_block(const RpmRepo *repo, size_t i)
{
    return (repo && i < repo->n_blocks) ? &repo->blocks[i] : NULL;
}

int rpm_repo_find_by_name(const RpmRepo *repo, const char *name,
                          size_t *out, int max)
{
    if (!repo)
        return 0;
    return table_lookup(repo->names, repo->nbuckets, name, out, max);
}

int rpm_repo_find_providers(const RpmRepo *repo, const char *cap,
                            size_t *out, int max)
{
    if (!repo)
        return 0;
    return table_lookup(repo->provides, repo->nbuckets, cap, out, max);
}

/* ── Field accessors ─────────────────────────────────────────────────────── */

static char *elem_dup(const RpmBlock *b, const char *name)
{
    const char *v;
    size_t      n;
    if (!elem_slice(b->start, b->end, name, &v, &n))
        return NULL;
    return pm_strndup(v, n);
}

char *rpm_block_name(const RpmBlock *b) { return elem_dup(b, "name"); }
char *rpm_block_arch(const RpmBlock *b) { return elem_dup(b, "arch"); }

char *rpm_block_href(const RpmBlock *b)
{
    const char *loc = bounded(b->start, b->end, "<location ");
    if (!loc)
        return NULL;
    const char *tag_end = memchr(loc, '>', (size_t)(b->end - loc));
    if (!tag_end)
        return NULL;
    return attr_dup(loc, tag_end, "href");
}

int rpm_block_evr(const RpmBlock *b, int *epoch, char **ver, char **rel)
{
    const char *v = bounded(b->start, b->end, "<version ");
    if (!v)
        return -1;
    const char *tag_end = memchr(v, '>', (size_t)(b->end - v));
    if (!tag_end)
        return -1;

    *ver = attr_dup(v, tag_end, "ver");
    *rel = attr_dup(v, tag_end, "rel");
    char *e = attr_dup(v, tag_end, "epoch");
    *epoch = e ? atoi(e) : 0;
    pm_free(e);
    return *ver ? 0 : -1;
}

int rpm_block_digest(const RpmBlock *b, Digest *out)
{
    for (const char *cs = b->start;
         (cs = bounded(cs, b->end, "<checksum ")) != NULL; cs++) {
        const char *tag_end = memchr(cs, '>', (size_t)(b->end - cs));
        if (!tag_end)
            break;
        char      *ty   = attr_dup(cs, tag_end, "type");
        DigestAlgo algo = digest_algo_from_name(ty);
        pm_free(ty);
        if (algo == DIGEST_NONE)
            continue;
        const char *val = tag_end + 1;
        const char *end = bounded(val, b->end, "</checksum>");
        if (!end)
            return -1;
        char *hex = pm_strndup(val, (size_t)(end - val));
        digest_set(out, algo, DIGEST_ENC_HEX, hex);
        pm_free(hex);
        return 0;
    }
    return -1;
}

/* ── Capability parsing ──────────────────────────────────────────────────── */

/* parse_entry — read one <rpm:entry .../> tag into `out`. */
static int parse_entry(const char *e, const char *tag_end, RpmCap *out)
{
    memset(out, 0, sizeof(*out));

    if (!attr_slice(e, tag_end, "name", &out->name, &out->name_len) ||
        out->name_len == 0)
        return -1;

    char *fl = attr_dup(e, tag_end, "flags");
    if (fl) {
        snprintf(out->flags, sizeof(out->flags), "%s", fl);
        pm_free(fl);
    }
    out->ver = attr_dup(e, tag_end, "ver");
    out->rel = attr_dup(e, tag_end, "rel");
    char *ep = attr_dup(e, tag_end, "epoch");
    out->epoch = ep ? atoi(ep) : 0;
    pm_free(ep);
    return 0;
}

/*
 * skippable — capabilities no bundle needs to carry.
 *
 * rpmlib(...) is satisfied by the rpm binary itself and config(foo) by foo's
 * own package; neither is ever a separate download.  A name starting with '('
 * is a rich/boolean dependency ("(a or b)"), which needs a real SAT solver to
 * evaluate — those are counted and reported rather than silently dropped.
 */
static int skippable(const char *name, size_t len, int *is_rich)
{
    *is_rich = 0;
    if (len > 0 && name[0] == '(') {
        *is_rich = 1;
        return 1;
    }
    if (len > 7 && strncmp(name, "rpmlib(", 7) == 0)
        return 1;
    if (len > 7 && strncmp(name, "config(", 7) == 0)
        return 1;
    return 0;
}

RpmCap *rpm_block_requires(const RpmBlock *b, size_t *n_out, size_t *n_rich_out)
{
    *n_out = 0;
    if (n_rich_out)
        *n_rich_out = 0;

    const char *req = bounded(b->start, b->end, "<rpm:requires>");
    if (!req)
        return NULL;
    const char *rend = bounded(req, b->end, "</rpm:requires>");
    if (!rend)
        rend = b->end;

    size_t  cap = 16, n = 0;
    RpmCap *out = pm_malloc(cap * sizeof(RpmCap));

    for (const char *e = req;
         (e = bounded(e, rend, "<rpm:entry ")) != NULL; e += 11) {
        const char *tag_end = memchr(e, '>', (size_t)(rend - e));
        if (!tag_end)
            break;

        RpmCap c;
        if (parse_entry(e, tag_end, &c) != 0)
            continue;

        int is_rich;
        if (skippable(c.name, c.name_len, &is_rich)) {
            if (is_rich && n_rich_out)
                (*n_rich_out)++;
            rpm_cap_clear(&c);
            continue;
        }

        if (n == cap) {
            cap *= 2;
            out = pm_realloc(out, cap * sizeof(RpmCap));
        }
        out[n++] = c;
    }

    *n_out = n;
    return out;
}

void rpm_cap_clear(RpmCap *c)
{
    if (!c)
        return;
    pm_free(c->ver);
    pm_free(c->rel);
    c->ver = NULL;
    c->rel = NULL;
}

void rpm_caps_free(RpmCap *caps, size_t n)
{
    if (!caps)
        return;
    for (size_t i = 0; i < n; i++)
        rpm_cap_clear(&caps[i]);
    pm_free(caps);
}

int rpm_block_provides_matching(const RpmBlock *b, const char *name,
                                RpmCap *out)
{
    const char *prov = bounded(b->start, b->end, "<rpm:provides>");
    if (!prov)
        return 0;
    const char *pend = bounded(prov, b->end, "</rpm:provides>");
    if (!pend)
        pend = b->end;

    size_t want = strlen(name);
    for (const char *e = prov;
         (e = bounded(e, pend, "<rpm:entry ")) != NULL; e += 11) {
        const char *tag_end = memchr(e, '>', (size_t)(pend - e));
        if (!tag_end)
            break;
        RpmCap c;
        if (parse_entry(e, tag_end, &c) != 0)
            continue;
        if (c.name_len == want && memcmp(c.name, name, want) == 0) {
            *out = c;
            return 1;
        }
        rpm_cap_clear(&c);
    }
    return 0;
}

/* ── Version satisfaction ────────────────────────────────────────────────── */

int rpm_cap_satisfied_by(const RpmCap *req, const RpmCap *prov)
{
    /* An unversioned requirement is met by the mere existence of a provider. */
    if (!req->flags[0] || !req->ver)
        return 1;

    /* A provider with no version on its provides entry (the common case for
     * soname and virtual capabilities) is treated as satisfying anything:
     * rpm itself resolves these by name. */
    if (!prov->ver)
        return 1;

    int cmp;
    if (req->epoch != prov->epoch) {
        cmp = prov->epoch > req->epoch ? 1 : -1;
    } else {
        cmp = rpm_vercmp(prov->ver, req->ver);
        if (cmp == 0 && req->rel && prov->rel)
            cmp = rpm_vercmp(prov->rel, req->rel);
    }

    if (strcmp(req->flags, "EQ") == 0) return cmp == 0;
    if (strcmp(req->flags, "GE") == 0) return cmp >= 0;
    if (strcmp(req->flags, "GT") == 0) return cmp >  0;
    if (strcmp(req->flags, "LE") == 0) return cmp <= 0;
    if (strcmp(req->flags, "LT") == 0) return cmp <  0;
    return 1;   /* unknown flag: do not exclude a candidate over it */
}
