# embed_scripts.cmake — turn the install scripts into an embeddable C header.
#
# Invoked at build time via:
#   cmake -DSCRIPTS_DIR=<dir> -DOUTPUT=<header> -P cmake/embed_scripts.cmake
#
# Each scripts/install_<name>.sh is read as raw bytes and emitted as a
# NUL-terminated `static const unsigned char INSTALL_<NAME>_SH[]` array.  Going
# through HEX avoids any C string-literal escaping of quotes, newlines, or
# semicolons, and needs no external tools (xxd/objcopy) — just CMake.

set(_out "/* Auto-generated by cmake/embed_scripts.cmake -- do not edit. */\n")
string(APPEND _out "#ifndef PACKMULE_BUNDLE_SCRIPTS_H\n")
string(APPEND _out "#define PACKMULE_BUNDLE_SCRIPTS_H\n\n")

foreach(_name pypi npm rpm)
    set(_path "${SCRIPTS_DIR}/install_${_name}.sh")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "embed_scripts: missing script ${_path}")
    endif()

    file(READ "${_path}" _hex HEX)
    # "2321..." -> "0x23,0x21,..."
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

    string(TOUPPER "${_name}" _upper)
    string(APPEND _out
        "static const unsigned char INSTALL_${_upper}_SH[] = {\n"
        "    ${_bytes}0x00\n"
        "};\n\n")
endforeach()

string(APPEND _out "#endif /* PACKMULE_BUNDLE_SCRIPTS_H */\n")

file(WRITE "${OUTPUT}" "${_out}")
