# embed_scripts.cmake — turn the install scripts into an embeddable C header.
#
# Invoked at build time via:
#   cmake -DSCRIPTS_DIR=<dir> -DOUTPUT=<header> -P cmake/embed_scripts.cmake
#
# Each scripts/install_<name>.sh is read as raw bytes and emitted as a
# NUL-terminated `static const unsigned char INSTALL_<NAME>_SH[]` array.  Going
# through HEX avoids any C string-literal escaping of quotes, newlines, or
# semicolons, and needs no external tools (xxd/objcopy) — just CMake.

set(_out "/* Auto-generated by cmake/embed_scripts.cmake -- do not edit. */\n")
string(APPEND _out "#ifndef PACKMULE_BUNDLE_SCRIPTS_H\n")
string(APPEND _out "#define PACKMULE_BUNDLE_SCRIPTS_H\n\n")

# The shared bundle-verification helper is spliced into each install script at
# its "#__PACKMULE_VERIFY__" marker, so the generated install.sh stays a single
# self-contained file while the helper remains one lintable shell source.
set(_verify_path "${SCRIPTS_DIR}/verify_bundle.sh")
if(NOT EXISTS "${_verify_path}")
    message(FATAL_ERROR "embed_scripts: missing ${_verify_path}")
endif()
file(READ "${_verify_path}" _verify)

foreach(_name pypi npm rpm)
    set(_path "${SCRIPTS_DIR}/install_${_name}.sh")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "embed_scripts: missing script ${_path}")
    endif()

    file(READ "${_path}" _script)
    string(FIND "${_script}" "#__PACKMULE_VERIFY__" _marker)
    if(_marker EQUAL -1)
        message(FATAL_ERROR
            "embed_scripts: ${_path} has no #__PACKMULE_VERIFY__ marker")
    endif()
    string(REPLACE "#__PACKMULE_VERIFY__" "${_verify}" _script "${_script}")

    # Round-trip through a file so the bytes can be read back as HEX without
    # needing string(HEX), which is CMake >= 3.18 only.
    set(_merged "${OUTPUT}.${_name}.sh")
    file(WRITE "${_merged}" "${_script}")
    file(READ "${_merged}" _hex HEX)
    file(REMOVE "${_merged}")
    # "2321..." -> "0x23,0x21,..."
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

    string(TOUPPER "${_name}" _upper)
    string(APPEND _out
        "static const unsigned char INSTALL_${_upper}_SH[] = {\n"
        "    ${_bytes}0x00\n"
        "};\n\n")
endforeach()

string(APPEND _out "#endif /* PACKMULE_BUNDLE_SCRIPTS_H */\n")

file(WRITE "${OUTPUT}" "${_out}")
